import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

type SectionRow = {
  label: string;
  totalMinutes: number;
  billableAmountCents: number;
};

export type BuildReportPdfInput = {
  title: string;
  periodLabel: string;
  generatedByName: string;
  totalMinutes: number;
  totalBillableAmountCents: number;
  byProject: SectionRow[];
  byMember: SectionRow[];
  byActivity: SectionRow[];
};

const formatCurrency = (amountCents: number): string =>
  new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(amountCents / 100);

const formatHours = (minutes: number): string => `${(minutes / 60).toFixed(2)} h`;

const drawSection = (
  page: ReturnType<PDFDocument["addPage"]>,
  title: string,
  rows: SectionRow[],
  y: number,
  bodyFont: Awaited<ReturnType<PDFDocument["embedFont"]>>,
): number => {
  page.drawText(title, {
    x: 50,
    y,
    size: 11,
    font: bodyFont,
    color: rgb(0.16, 0.16, 0.16),
  });

  let cursorY = y - 18;
  for (const row of rows.slice(0, 8)) {
    page.drawText(
      `${row.label}  |  ${formatHours(row.totalMinutes)}  |  ${formatCurrency(row.billableAmountCents)}`,
      {
        x: 60,
        y: cursorY,
        size: 9,
        font: bodyFont,
        color: rgb(0.22, 0.22, 0.22),
      },
    );
    cursorY -= 14;
  }

  return cursorY - 10;
};

export const buildReportPdf = async (
  input: BuildReportPdfInput,
): Promise<Uint8Array> => {
  const document = await PDFDocument.create();
  const page = document.addPage([595, 842]);
  const titleFont = await document.embedFont(StandardFonts.HelveticaBold);
  const bodyFont = await document.embedFont(StandardFonts.Helvetica);

  page.drawRectangle({
    x: 0,
    y: 790,
    width: 595,
    height: 52,
    color: rgb(0.11, 0.17, 0.24),
  });

  page.drawText(input.title, {
    x: 48,
    y: 812,
    size: 18,
    font: titleFont,
    color: rgb(0.95, 0.97, 0.99),
  });

  page.drawText(`Period: ${input.periodLabel}`, {
    x: 48,
    y: 770,
    size: 10,
    font: bodyFont,
    color: rgb(0.20, 0.20, 0.20),
  });

  page.drawText(`Generated by: ${input.generatedByName}`, {
    x: 270,
    y: 770,
    size: 10,
    font: bodyFont,
    color: rgb(0.20, 0.20, 0.20),
  });

  page.drawText(
    `Total: ${formatHours(input.totalMinutes)} · ${formatCurrency(input.totalBillableAmountCents)}`,
    {
      x: 48,
      y: 745,
      size: 12,
      font: titleFont,
      color: rgb(0.11, 0.17, 0.24),
    },
  );

  let y = 712;
  y = drawSection(page, "By Project", input.byProject, y, bodyFont);
  y = drawSection(page, "By Member", input.byMember, y, bodyFont);
  drawSection(page, "By Activity", input.byActivity, y, bodyFont);

  return document.save();
};
